name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Use minimal required permissions for the Pages workflow
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Diagnostics (git / env / files)
        run: |
          echo "=== pwd ==="; pwd
          echo "=== ls -la ==="; ls -la
          echo "=== git --version ==="; git --version
          echo "=== git status ==="; git status --porcelain || true
          echo "=== git remote -v ==="; git remote -v || true
          echo "=== git branch -a ==="; git branch -a || true
          echo "=== env (select) ==="; env | grep -E 'GITHUB|RUNNER|INPUT|TOKEN' || true

      - name: Configure Pages
        uses: actions/configure-pages@v3

      - name: Upload static content
        uses: actions/upload-pages-artifact@v1
        with:
          path: './'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
